Repository everoute/container, pull requests merged in 2025-09, with the labels that each got.

#56 feat: blob fetch download interface
  remotes/file.go
  remotes/file_download.go
  remotes/file_download_test.go
  remotes/testdata/example-zstd.tar
Labels: size/m

#58 feat: make container creation concurrently
  client/clienttest/runtime.go
  plugin/executor.go
Labels: size/m, size/s

#59 fix: allow all devices on systemd cgroup
  client/runtime.go
Labels: size/s
